%% PENALIZED MAXIMUM LIKELIHOOD ESTIMATION
% Bivariate application to Pb-Zn geochemical data
%
% This script reproduces the bivariate geochemical application
% described in the paper. For each Czech administrative district
% and each number of inner knots g = h, the pair of penalization
% parameters (rho_x,rho_y) is selected by K-fold cross-validation.
%
% Required auxiliary functions:
%   ML_pen_fun_grad.m
%   auxiliary integration functions used by ML_pen_fun_grad.m

clear;
clc;
close all;

%% =========================================================
% LOAD DATA
%% =========================================================

opts = detectImportOptions('data.csv','Delimiter',';');

opts = setvartype(opts,{'Pb','Zn'},'string');

data = readtable('data.csv',opts);

data.Pb = ...
    str2double( ...
        replace(data.Pb,',','.'));

data.Zn = ...
    str2double( ...
        replace(data.Zn,',','.'));

%% =========================================================
% COMMON DOMAIN
%% =========================================================

a = 1.358;
b = 5.716;

c = 1.457;
d = 5.665;

%% =========================================================
% SETTINGS
%% =========================================================

K = 5;                  % number of cross-validation folds

g_grid = 1:10;          % g = h

rho_x_grid = logspace(-4,1,20);
rho_y_grid = logspace(-4,1,20);

k_deg = 3;              % spline degree in Pb direction
l_deg = 3;              % spline degree in Zn direction

d_x = 1;                % difference order in Pb direction
d_y = 1;                % difference order in Zn direction

n_grid = 200;           % grid size for numerical integration

%% =========================================================
% OPTIMIZATION OPTIONS
%% =========================================================

opts_fmin = optimoptions('fminunc', ...
    'Algorithm','quasi-newton', ...
    'SpecifyObjectiveGradient',true, ...
    'Display','off', ...
    'MaxFunctionEvaluations',5e4, ...
    'MaxIterations',2e3);

%% =========================================================
% ADMINISTRATIVE DISTRICTS
%% =========================================================

regions = ...
    string(unique(data.NAZEV));

sortkey = ...
    lower(regions);

sortkey = ...
    replace(sortkey,'ch','h~');

[~,idx] = ...
    sort(sortkey);

regions = ...
    regions(idx);

%% =========================================================
% RESULTS
%% =========================================================

results = table();

%% =========================================================
% LOOP OVER DISTRICTS
%% =========================================================

for iregion = 1:numel(regions)

    region = ...
        regions(iregion);

    mask = ...
        strcmpi(data.NAZEV,region);

    x = ...
        data.Pb(mask);

    y = ...
        data.Zn(mask);

    valid = ...
        ~isnan(x) & ~isnan(y);

    x = ...
        x(valid);

    y = ...
        y(valid);

    N = ...
        length(x);

    fprintf( ...
        '\nRegion: %s (%d/%d), N = %d\n', ...
        region, ...
        iregion, ...
        numel(regions), ...
        N);

    %% -----------------------------------------------------
    % Integration grid
    %% -----------------------------------------------------

    xq = ...
        linspace(a,b,n_grid);

    yq = ...
        linspace(c,d,n_grid);

    %% -----------------------------------------------------
    % Cross-validation partition
    %% -----------------------------------------------------

    cv = ...
        cvpartition(N,'KFold',K);

    %% =====================================================
    % LOOP OVER THE NUMBER OF INNER KNOTS
    %% =====================================================

    for g = g_grid

        h = g;

        fprintf('   g = h = %d\n',g);

        %% -------------------------------------------------
        % ZB-spline basis in Pb direction
        %% -------------------------------------------------

        lambda = ...
            linspace(a,b,g+2);

        Lambda = ...
            augknt(lambda,k_deg+1);

        Zsys_x = [];

        for i = 1:length(Lambda)-k_deg-2

            Bx = ...
                spmak( ...
                    Lambda(i:i+k_deg+2), ...
                    1);

            Zsys_x = ...
                [Zsys_x fnder(Bx)]; %#ok<AGROW>
        end

        n = ...
            length(Zsys_x);

        %% -------------------------------------------------
        % ZB-spline basis in Zn direction
        %% -------------------------------------------------

        mu = ...
            linspace(c,d,h+2);

        Mu = ...
            augknt(mu,l_deg+1);

        Zsys_y = [];

        for j = 1:length(Mu)-l_deg-2

            By = ...
                spmak( ...
                    Mu(j:j+l_deg+2), ...
                    1);

            Zsys_y = ...
                [Zsys_y fnder(By)]; %#ok<AGROW>
        end

        m = ...
            length(Zsys_y);

        %% -------------------------------------------------
        % Collocation matrices at observations
        %% -------------------------------------------------

        Zx = ...
            zeros(N,n);

        for i = 1:n

            Zx(:,i) = ...
                fnval(Zsys_x(i),x)';
        end

        Zy = ...
            zeros(N,m);

        for j = 1:m

            Zy(:,j) = ...
                fnval(Zsys_y(j),y)';
        end

        %% -------------------------------------------------
        % Collocation matrices on the integration grid
        %% -------------------------------------------------

        Zxq = ...
            zeros(length(xq),n);

        for i = 1:n

            Zxq(:,i) = ...
                fnval(Zsys_x(i),xq)';
        end

        Zyq = ...
            zeros(length(yq),m);

        for j = 1:m

            Zyq(:,j) = ...
                fnval(Zsys_y(j),yq)';
        end

        %% -------------------------------------------------
        % Penalty matrices
        %% -------------------------------------------------

        D_x = ...
            diff(eye(n),d_x);

        P_x = ...
            D_x'*D_x;

        D_y = ...
            diff(eye(m),d_y);

        P_y = ...
            D_y'*D_y;

        P_x_kron = ...
            kron(eye(m),P_x);

        P_y_kron = ...
            kron(P_y,eye(n));

        %% -------------------------------------------------
        % Select (rho_x,rho_y) by K-fold cross-validation
        %% -------------------------------------------------

        cv_score = ...
            zeros( ...
                length(rho_x_grid), ...
                length(rho_y_grid));

        theta0 = ...
            zeros(n*m+n+m,1);

        for ix = 1:length(rho_x_grid)

            rho_x = ...
                rho_x_grid(ix);

            for iy = 1:length(rho_y_grid)

                rho_y = ...
                    rho_y_grid(iy);

                fold_score = ...
                    zeros(K,1);

                for kfold = 1:K

                    idx_train = ...
                        training(cv,kfold);

                    idx_test = ...
                        test(cv,kfold);

                    %% training data

                    Zx_train = ...
                        Zx(idx_train,:);

                    Zy_train = ...
                        Zy(idx_train,:);

                    c_train = ...
                        sum(Zx_train,1)';

                    d_train = ...
                        sum(Zy_train,1)';

                    N_train = ...
                        sum(idx_train);

                    %% validation data

                    Zx_test = ...
                        Zx(idx_test,:);

                    Zy_test = ...
                        Zy(idx_test,:);

                    c_test = ...
                        sum(Zx_test,1)';

                    d_test = ...
                        sum(Zy_test,1)';

                    N_test = ...
                        sum(idx_test);

                    %% fit on the training sample

                    objective = @(theta) ...
                        ML_pen_fun_grad( ...
                            theta, ...
                            Zx_train, ...
                            Zy_train, ...
                            c_train, ...
                            d_train, ...
                            n, ...
                            m, ...
                            N_train, ...
                            xq, ...
                            yq, ...
                            Zxq, ...
                            Zyq, ...
                            P_x_kron, ...
                            P_y_kron, ...
                            P_x, ...
                            P_y, ...
                            rho_x, ...
                            rho_y);

                    theta_hat = ...
                        fminunc( ...
                            objective, ...
                            theta0, ...
                            opts_fmin);

                    %% validation negative log-likelihood

                    validation_objective = @(theta) ...
                        ML_pen_fun_grad( ...
                            theta, ...
                            Zx_test, ...
                            Zy_test, ...
                            c_test, ...
                            d_test, ...
                            n, ...
                            m, ...
                            N_test, ...
                            xq, ...
                            yq, ...
                            Zxq, ...
                            Zyq, ...
                            P_x_kron, ...
                            P_y_kron, ...
                            P_x, ...
                            P_y, ...
                            0, ...
                            0);

                    fold_score(kfold) = ...
                        validation_objective(theta_hat);
                end

                cv_score(ix,iy) = ...
                    mean(fold_score);
            end
        end

        %% -------------------------------------------------
        % Optimal penalization parameters
        %% -------------------------------------------------

        [cv_min,index_min] = ...
            min(cv_score(:));

        [best_ix,best_iy] = ...
            ind2sub( ...
                size(cv_score), ...
                index_min);

        rho_x_opt = ...
            rho_x_grid(best_ix);

        rho_y_opt = ...
            rho_y_grid(best_iy);

        %% -------------------------------------------------
        % Final fit using the complete district sample
        %% -------------------------------------------------

        c_all = ...
            sum(Zx,1)';

        d_all = ...
            sum(Zy,1)';

        objective = @(theta) ...
            ML_pen_fun_grad( ...
                theta, ...
                Zx, ...
                Zy, ...
                c_all, ...
                d_all, ...
                n, ...
                m, ...
                N, ...
                xq, ...
                yq, ...
                Zxq, ...
                Zyq, ...
                P_x_kron, ...
                P_y_kron, ...
                P_x, ...
                P_y, ...
                rho_x_opt, ...
                rho_y_opt);

        theta_final = ...
            fminunc( ...
                objective, ...
                theta0, ...
                opts_fmin);

        %% -------------------------------------------------
        % Estimated spline in L^2_0(Omega)
        %% -------------------------------------------------

        z_final = ...
            theta_final(1:n*m);

        v_final = ...
            theta_final(n*m+1:n*m+n);

        u_final = ...
            theta_final(n*m+n+1:end);

        Z_final = ...
            reshape(z_final,n,m);

        s_interaction = ...
            Zxq*Z_final*Zyq';

        s_x = ...
            Zxq*v_final;

        s_y = ...
            Zyq*u_final;

        s_est = ...
            s_interaction ...
            + s_x ...
            + s_y';

        %% -------------------------------------------------
        % Estimated probability density
        %% -------------------------------------------------

        smax = ...
            max(s_est(:));

        f_est = ...
            exp(s_est-smax);

        normalizing_constant = ...
            trapz( ...
                yq, ...
                trapz(xq,f_est,1), ...
                2);

        f_est = ...
            f_est/normalizing_constant;

        %% -------------------------------------------------
        % Store results
        %% -------------------------------------------------

        new_row = ...
            table( ...
                region, ...
                N, ...
                K, ...
                d_x, ...
                d_y, ...
                g, ...
                h, ...
                rho_x_opt, ...
                rho_y_opt, ...
                cv_min, ...
                'VariableNames', { ...
                    'region', ...
                    'N', ...
                    'K', ...
                    'd_x', ...
                    'd_y', ...
                    'g', ...
                    'h', ...
                    'rho_x_opt', ...
                    'rho_y_opt', ...
                    'CV'});

        results = ...
            [results; new_row]; %#ok<AGROW>

        fprintf( ...
            ['      rho_x = %.4g, rho_y = %.4g, ' ...
             'CV = %.4f\n'], ...
            rho_x_opt, ...
            rho_y_opt, ...
            cv_min);
    end
end

%% =========================================================
% SUMMARY OVER DISTRICTS
%% =========================================================

summary = ...
    groupsummary( ...
        results, ...
        {'g','h'}, ...
        {'mean','median','std'}, ...
        {'rho_x_opt','rho_y_opt','CV'});

disp(summary);

%% =========================================================
% SAVE RESULTS
%% =========================================================

writetable( ...
    results, ...
    sprintf( ...
        'application_2D_Pb_Zn_dx%d_dy%d_K%d.csv', ...
        d_x,d_y,K));

writetable( ...
    summary, ...
    sprintf( ...
        'application_2D_Pb_Zn_dx%d_dy%d_K%d_summary.csv', ...
        d_x,d_y,K));