%% PENALIZED MAXIMUM LIKELIHOOD ESTIMATION
% Bivariate simulation study
%
% For each simulated sample and each number of inner knots g = h,
% the pair of penalization parameters (rho_x,rho_y) is selected
% by K-fold cross-validation.
%
% Required auxiliary functions:
%   ML_pen_fun_grad.m
%   auxiliary integration functions used by ML_pen_fun_grad.m

clear;
clc;
close all;

%% =========================================================
% SETTINGS
%% =========================================================

density = 1;            % 1 = Normal, 2 = Bimodal

N = 3000;               % sample size
K = 5;                  % number of cross-validation folds

n_simulations = 100;    % number of simulation runs

g_grid = 1:10;          % g = h

rho_x_grid = logspace(-4,1,20);
rho_y_grid = logspace(-4,1,20);

k_deg = 2;              % spline degree in x-direction
l_deg = 2;              % spline degree in y-direction

d_x = 1;                % difference order in x-direction
d_y = 1;                % difference order in y-direction

n_grid = 200;           % grid size for numerical integration

%% =========================================================
% OPTIMIZATION OPTIONS
%% =========================================================

opts = optimoptions('fminunc', ...
    'Algorithm','quasi-newton', ...
    'SpecifyObjectiveGradient',true, ...
    'Display','off', ...
    'MaxFunctionEvaluations',5e4, ...
    'MaxIterations',2e3);

%% =========================================================
% RESULTS
%% =========================================================

results = table();

%% =========================================================
% SIMULATION
%% =========================================================

for isim = 1:n_simulations

    fprintf('\nSimulation %d/%d\n', ...
        isim,n_simulations);

    %% -----------------------------------------------------
    % Generate data
    %% -----------------------------------------------------

    switch density

        case 1
            density_name = "Normal";

            mu = [0 0];

            Sigma = [1 0; ...
                     0 1];

            X = mvnrnd(mu,Sigma,N);

            a = -3;
            b = 3;

            c = -3;
            d = 3;

        case 2
            density_name = "Bimodal";

            w1 = 0.5;
            w2 = 0.5;

            n1 = round(w1*N);
            n2 = N-n1;

            mu1 = [-1 -1];

            Sigma1 = [1.6  0.2; ...
                      0.2  0.5];

            mu2 = [1 1];

            Sigma2 = [ 1.6 -0.2; ...
                      -0.2  0.5];

            X1 = mvnrnd(mu1,Sigma1,n1);
            X2 = mvnrnd(mu2,Sigma2,n2);

            X = [X1; X2];

            X = X(randperm(N),:);

            a = -4;
            b = 4;

            c = -3;
            d = 3;

        otherwise
            error('Unknown density.');
    end

    x = X(:,1);
    y = X(:,2);

    %% -----------------------------------------------------
    % Evaluation grid
    %% -----------------------------------------------------

    xq = linspace(a,b,n_grid);
    yq = linspace(c,d,n_grid);

    [XX,YY] = ndgrid(xq,yq);

    grid_points = ...
        [XX(:),YY(:)];

    %% -----------------------------------------------------
    % True density
    %% -----------------------------------------------------

    switch density

        case 1
            f_true = ...
                mvnpdf(grid_points,mu,Sigma);

        case 2
            f_true = ...
                w1*mvnpdf(grid_points,mu1,Sigma1) + ...
                w2*mvnpdf(grid_points,mu2,Sigma2);
    end

    f_true = ...
        reshape(f_true,n_grid,n_grid);

    %% -----------------------------------------------------
    % clr representation of the true density
    %% -----------------------------------------------------

    log_f_true = log(f_true);

    mean_log_f_true = ...
        trapz( ...
            yq, ...
            trapz(xq,log_f_true,1), ...
            2) ...
        / ((b-a)*(d-c));

    clr_true = ...
        log_f_true-mean_log_f_true;

    %% -----------------------------------------------------
    % Cross-validation partition
    %% -----------------------------------------------------

    cv = ...
        cvpartition(N,'KFold',K);

    %% =====================================================
    % LOOP OVER THE NUMBER OF INNER KNOTS
    %% =====================================================

    for g = g_grid

        h = g;

        fprintf('   g = h = %d\n',g);

        %% -------------------------------------------------
        % ZB-spline basis in x-direction
        %% -------------------------------------------------

        lambda = ...
            linspace(a,b,g+2);

        Lambda = ...
            augknt(lambda,k_deg+1);

        Zsys_x = [];

        for i = 1:length(Lambda)-k_deg-2

            Bx = ...
                spmak( ...
                    Lambda(i:i+k_deg+2), ...
                    1);

            Zsys_x = ...
                [Zsys_x fnder(Bx)]; %#ok<AGROW>
        end

        n = length(Zsys_x);

        %% -------------------------------------------------
        % ZB-spline basis in y-direction
        %% -------------------------------------------------

        mu_knots = ...
            linspace(c,d,h+2);

        Mu = ...
            augknt(mu_knots,l_deg+1);

        Zsys_y = [];

        for j = 1:length(Mu)-l_deg-2

            By = ...
                spmak( ...
                    Mu(j:j+l_deg+2), ...
                    1);

            Zsys_y = ...
                [Zsys_y fnder(By)]; %#ok<AGROW>
        end

        m = length(Zsys_y);

        %% -------------------------------------------------
        % Collocation matrices at observations
        %% -------------------------------------------------

        Zx = zeros(N,n);

        for i = 1:n
            Zx(:,i) = fnval(Zsys_x(i),x)';
        end

        Zy = zeros(N,m);

        for j = 1:m
            Zy(:,j) = fnval(Zsys_y(j),y)';
        end

        %% -------------------------------------------------
        % Collocation matrices on the integration grid
        %% -------------------------------------------------

        Zxq = zeros(length(xq),n);

        for i = 1:n
            Zxq(:,i) = fnval(Zsys_x(i),xq)';
        end

        Zyq = zeros(length(yq),m);

        for j = 1:m
            Zyq(:,j) = fnval(Zsys_y(j),yq)';
        end

        %% -------------------------------------------------
        % Penalty matrices
        %% -------------------------------------------------

        D_x = diff(eye(n),d_x);
        P_x = D_x'*D_x;

        D_y = diff(eye(m),d_y);
        P_y = D_y'*D_y;

        P_x_kron = ...
            kron(eye(m),P_x);

        P_y_kron = ...
            kron(P_y,eye(n));

        %% -------------------------------------------------
        % Select (rho_x,rho_y) by K-fold cross-validation
        %% -------------------------------------------------

        cv_score = ...
            zeros( ...
                length(rho_x_grid), ...
                length(rho_y_grid));

        theta0 = ...
            zeros(n*m+n+m,1);

        for ix = 1:length(rho_x_grid)

            rho_x = ...
                rho_x_grid(ix);

            for iy = 1:length(rho_y_grid)

                rho_y = ...
                    rho_y_grid(iy);

                fold_score = ...
                    zeros(K,1);

                for kfold = 1:K

                    idx_train = ...
                        training(cv,kfold);

                    idx_test = ...
                        test(cv,kfold);

                    %% training data

                    Zx_train = ...
                        Zx(idx_train,:);

                    Zy_train = ...
                        Zy(idx_train,:);

                    c_train = ...
                        sum(Zx_train,1)';

                    d_train = ...
                        sum(Zy_train,1)';

                    N_train = ...
                        sum(idx_train);

                    %% validation data

                    Zx_test = ...
                        Zx(idx_test,:);

                    Zy_test = ...
                        Zy(idx_test,:);

                    c_test = ...
                        sum(Zx_test,1)';

                    d_test = ...
                        sum(Zy_test,1)';

                    N_test = ...
                        sum(idx_test);

                    %% fit on the training sample

                    objective = @(theta) ...
                        ML_pen_fun_grad( ...
                            theta, ...
                            Zx_train, ...
                            Zy_train, ...
                            c_train, ...
                            d_train, ...
                            n, ...
                            m, ...
                            N_train, ...
                            xq, ...
                            yq, ...
                            Zxq, ...
                            Zyq, ...
                            P_x_kron, ...
                            P_y_kron, ...
                            P_x, ...
                            P_y, ...
                            rho_x, ...
                            rho_y);

                    theta_hat = ...
                        fminunc( ...
                            objective, ...
                            theta0, ...
                            opts);

                    %% validation negative log-likelihood

                    validation_objective = @(theta) ...
                        ML_pen_fun_grad( ...
                            theta, ...
                            Zx_test, ...
                            Zy_test, ...
                            c_test, ...
                            d_test, ...
                            n, ...
                            m, ...
                            N_test, ...
                            xq, ...
                            yq, ...
                            Zxq, ...
                            Zyq, ...
                            P_x_kron, ...
                            P_y_kron, ...
                            P_x, ...
                            P_y, ...
                            0, ...
                            0);

                    fold_score(kfold) = ...
                        validation_objective(theta_hat);
                end

                cv_score(ix,iy) = ...
                    mean(fold_score);
            end
        end

        %% -------------------------------------------------
        % Optimal penalization parameters
        %% -------------------------------------------------

        [cv_min,index_min] = ...
            min(cv_score(:));

        [best_ix,best_iy] = ...
            ind2sub( ...
                size(cv_score), ...
                index_min);

        rho_x_opt = ...
            rho_x_grid(best_ix);

        rho_y_opt = ...
            rho_y_grid(best_iy);

        %% -------------------------------------------------
        % Final fit
        %% -------------------------------------------------

        c_all = sum(Zx,1)';
        d_all = sum(Zy,1)';

        objective = @(theta) ...
            ML_pen_fun_grad( ...
                theta, ...
                Zx, ...
                Zy, ...
                c_all, ...
                d_all, ...
                n, ...
                m, ...
                N, ...
                xq, ...
                yq, ...
                Zxq, ...
                Zyq, ...
                P_x_kron, ...
                P_y_kron, ...
                P_x, ...
                P_y, ...
                rho_x_opt, ...
                rho_y_opt);

        theta_final = ...
            fminunc( ...
                objective, ...
                theta0, ...
                opts);

        %% -------------------------------------------------
        % Estimated spline in L^2_0(Omega)
        %% -------------------------------------------------

        z_final = ...
            theta_final(1:n*m);

        v_final = ...
            theta_final(n*m+1:n*m+n);

        u_final = ...
            theta_final(n*m+n+1:end);

        Z_final = ...
            reshape(z_final,n,m);

        s_interaction = ...
            Zxq*Z_final*Zyq';

        s_x = ...
            Zxq*v_final;

        s_y = ...
            Zyq*u_final;

        s_est = ...
            s_interaction ...
            + s_x ...
            + s_y';

        %% -------------------------------------------------
        % Estimated probability density
        %% -------------------------------------------------

        smax = max(s_est(:));

        f_est = exp(s_est-smax);

        normalizing_constant = ...
            trapz( ...
                yq, ...
                trapz(xq,f_est,1), ...
                2);

        f_est = ...
            f_est/normalizing_constant;

        %% -------------------------------------------------
        % Normalized integrated squared error
        %% -------------------------------------------------

        squared_error = ...
            (clr_true-s_est).^2;

        NISE = ...
            trapz( ...
                yq, ...
                trapz(xq,squared_error,1), ...
                2) ...
            / ((b-a)*(d-c));

        %% -------------------------------------------------
        % Store results
        %% -------------------------------------------------

        new_row = ...
            table( ...
                isim, ...
                density_name, ...
                N, ...
                K, ...
                g, ...
                h, ...
                rho_x_opt, ...
                rho_y_opt, ...
                cv_min, ...
                NISE, ...
                'VariableNames', { ...
                    'simulation', ...
                    'density', ...
                    'N', ...
                    'K', ...
                    'g', ...
                    'h', ...
                    'rho_x_opt', ...
                    'rho_y_opt', ...
                    'CV', ...
                    'NISE'});

        results = ...
            [results; new_row]; %#ok<AGROW>

        fprintf( ...
            ['      rho_x = %.4g, rho_y = %.4g, ' ...
             'CV = %.4f, NISE = %.4g\n'], ...
            rho_x_opt, ...
            rho_y_opt, ...
            cv_min, ...
            NISE);
    end
end

%% =========================================================
% SUMMARY
%% =========================================================

summary = ...
    groupsummary( ...
        results, ...
        {'g','h'}, ...
        {'mean','median','std'}, ...
        {'rho_x_opt','rho_y_opt','CV','NISE'});

disp(summary);

%% =========================================================
% SAVE RESULTS
%% =========================================================

writetable( ...
    results, ...
    sprintf( ...
        'simulation_2D_%s_N%d_K%d.csv', ...
        density_name,N,K));

writetable( ...
    summary, ...
    sprintf( ...
        'simulation_2D_%s_N%d_K%d_summary.csv', ...
        density_name,N,K));